# System Constants Configuration
# This file defines system-wide thresholds, API endpoints, and retry settings.
# Usually you don't need to change these unless you have specific requirements.

# Year filtering
min_year: 2024  # Papers published before this year are filtered out

# Relevance scoring
relevance_threshold: 6  # Minimum LLM score (0-10) to include a paper
score_cache_path: "./docs/relevance_cache.json"  # Persistent score cache location

# Special score values:
# -1 = Scoring failed (API error, quota exceeded, etc.) - will be retried on next run
# Papers with score=-1 are excluded from results but marked for retry

# API endpoints
arxiv_api_url: "http://export.arxiv.org/api/query"
arxiv_base_url: "http://arxiv.org/"
semantic_scholar_url: "https://api.semanticscholar.org/graph/v1/paper/"
huggingface_papers_url: "https://huggingface.co/api/papers/"
github_search_url: "https://api.github.com/search/repositories"

# API retry settings
arxiv:
  max_retries: 3
  retry_delay: 3  # seconds
  timeout: 30  # seconds
  max_query_clauses: 8  # Max OR clauses per API call (splits long queries)

semantic_scholar:
  rate_limit_pause: 5  # seconds to pause on 429 rate-limit responses
  pagination_delay: 1  # seconds between pagination requests
  seed_paper_delay: 2  # seconds between different seed papers
  batch_size: 500  # papers per request
